# (PART) Data Manipulation and Data Aggregation {-}


# Starting Your Machine Learning Pipeline

## todo
+ since rmarkdown/knitr start a new session when building docs, can't access current spark context
+ either build from scratch, or persist rdds/dfs
+ alternatively, make ipynb in jupyter and save as md and render in book as md
+ no console output from rxHadoop shell wrappers, need to sink and show if want to see output
+ to cache results, might make sense to persist DFs and then reuse when needed
+ take a look at [sparkr-ext](https://github.com/hoxo-m/SparkRext)
+ and SKKU-SKT/ggplot2.SparkR

The first steps to start your machine learning and data science pipeline is to set your compute environment, and point to your data.

In Spark, you'll need to create a SparkContext. This constructor provides Spark with the details of the cluster: how and where to access it, additional package directories, etc. You'll use this constructor to create new RDDs or DataFrames. 

## Finding the SparkR Library

In order to create a Spark Context from your RStudio Server environment, you'll need to access the SparkR library. Since Spark 1.4, SparkR has shipped the R API directly with its core implementation. Therefore, since 1.4 you do not need to install Spark from CRAN or a development version from github, but you need to add the SparkR library to your library paths in order to access it. A system variable called "SPARK_HOME" has been set that points to the Spark installation directory, and in it you'll find subdirectories, "R/lib", containing the SparkR library. 


```{r-spark-lib-ls}
list.files(file.path(Sys.getenv("SPARK_HOME"), "R", "lib"))

```

To add the SparkR library to your library paths, use the `.libPaths` function to include the directory in the search path for R's library tree. The library paths could also be changed from in the `Rprofile`, either for the user or system wide. See the help on `?StartUp` for more details on R's startup mechanism.

```{r-sparkr-lib, eval = FALSE}
.libPaths(c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib"), .libPaths()))

```


## Creating a Spark Context

To create a SparkContext, you should use the `spark.init` function and pass in options for the environment parameters, application properties, any spark packages depended on, and any other additional Spark parameters. In order to create and manipulate DataFrames, we will need a SQLContext, which can be created from the SparkContext using the `sparkRSQL.init` function. 

```{r-spark-context, eval = FALSE}
library(SparkR)

sparkEnvir <- list(spark.executor.instance = '10',
                   spark.yarn.executor.memoryOverhead = '8000')

sc <- sparkR.init(
  sparkEnvir = sparkEnvir,
  sparkPackages = "com.databricks:spark-csv_2.10:1.3.0"
)

sqlContext <- sparkRSQL.init(sc)
```

We added the `sparkPackages` argument and set it to the value of `spark-csv` package provided by databricks. This will allow us to read csv objects into Spark DataFrames. Databricks are a prominent vendor for Spark, and are developers of many Spark packages (think of them as the RStudio of the Spark ecosystem). 

After you are done using your Spark session, you can terminate your backend to Spark by running `sparkR.stop()`.

## Creating DataFrames

Using our `sqlContext` variable, we can create DataFrames from local R data.frames, from Hive tables, or from other data sources. You could create a Spark DataFrame from a local R data.frame using the `createDataFrame` function, 

### From Local R data.frames

Creating Spark DataFrames from local R `data.frames` might not seem like a great idea. After all, if it can fit in an R data.frame, that means it can fit in a single node's memory, so why distribute it? It might be that you are testing your methods out on a sample dataset, and eventually you plan to scale out your analysis to larger datasets when your tests have passed. For expository purposes, this is a useful exercise, as it'll expose you to the fundamentals of Spark DataFrames, and the SparkR syntax.

As a first example, we'll import data from the `nycflight13` package into a Spark DataFrame, and use it's data aggregation functions to tabulate the number of flights to each destination of flights originating from JFK.

```{r-rdftosparkdf, eval = FALSE}
library(nycflights13)
flights <- createDataFrame(sqlContext, nycflights13::flights)
jfk_flights <- filter(flights, flights$origin == "JFK")
# Group the flights by destination and aggregate by the number of flights
dest_flights <- summarize(
  group_by(jkf_flights, jfk_flights$dest), 
  count = n(jfk_flights$dest)
  )
# Now sort by the `count` column and print the first few rows
head(arrange(dest_flights, desc(dest_flights$count)))

```

This same analysis could be streamlined using the `%>%` operator exposed by the magrittr package to improve the readability of the pipeline:

```{r-spark-magrittr, eval = FALSE}
library(magrittr)
dest_flights <- filter(flights, flights$origin == "JFK") %>% 
  group_by(flights$dest) %>% 
  summarize(count = n(flights$dest))
dest_flights %>% arrange(desc(dest_flights$count)) %>% head


```

### Creating DataFrames from CSV Files

Since we imported the spark-csv package, we can import CSV files into DataFrames. We will be using the full airlines dataset, which I assume you have already ingested into Blob storage by following the steps in Section \@ref(ingestion).

We have saved in our data directory a couple of data directories (virtually, everything in Azure Storage is a simple blob!). Let's see what we have in our directory using the `rxHadoopListFiles` command, which is simply a wrapper to hadoop shell command `hadoop fs -ls`

```{r-data-dir}
data_dir <- "/user/RevoShare/alizaidi"
rxHadoopListFiles(data_dir)

```

Taking a look at the individual directories, we can see how many files there are for the Airlines directory and Weather directory

```{r-air-weather}
rxHadoopCommand("fs -ls /user/RevoShare/alizaidi/AirOnTimeCSV | head")
rxHadoopCommand("fs -ls /user/RevoShare/alizaidi/delayDataLarge/WeatherRaw | head")

```

Let's read the airlines directory and the weather directory to Spark DataFrames. We will use the `read.df` function from the `spark.csv` package.

```{r-import-df, eval = FALSE}

```

Note that it took more than 6 minutes to load our airlines data into Spark DataFrames. However, subsequent operations on the `airDF` object will occur in-memory, and should be very fast.

Let's count the number of rows in each of our DataFrames and print the first few rows:

```{r-count-head, eval = FALSE}
library(SparkR)
lapply(list(airDF, weatherDF), count)
# [[1]]
# [1] 148619655
# 
# [[2]]
# [1] 14829028

lapply(list(airDF, weatherDF), head)
# [[1]]
#   YEAR MONTH DAY_OF_MONTH DAY_OF_WEEK    FL_DATE UNIQUE_CARRIER TAIL_NUM FL_NUM
# 1 1987    10            1           4 1987-10-01             AA               1
# 2 1987    10            2           5 1987-10-02             AA               1
# 3 1987    10            3           6 1987-10-03             AA               1
# 4 1987    10            4           7 1987-10-04             AA               1
# 5 1987    10            5           1 1987-10-05             AA               1
# 6 1987    10            6           2 1987-10-06             AA               1
#   ORIGIN_AIRPORT_ID ORIGIN ORIGIN_STATE_ABR DEST_AIRPORT_ID DEST DEST_STATE_ABR
# 1             12478    JFK               NY           12892  LAX             CA
# 2             12478    JFK               NY           12892  LAX             CA
# 3             12478    JFK               NY           12892  LAX             CA
# 4             12478    JFK               NY           12892  LAX             CA
# 5             12478    JFK               NY           12892  LAX             CA
# 6             12478    JFK               NY           12892  LAX             CA
#   CRS_DEP_TIME DEP_TIME DEP_DELAY DEP_DELAY_NEW DEP_DEL15 DEP_DELAY_GROUP TAXI_OUT
# 1          900      901         1             1         0               0         
# 2          900      901         1             1         0               0         
# 3          900      859        -1             0         0              -1         
# 4          900      900         0             0         0               0         
# 5          900      902         2             2         0               0         
# 6          900      900         0             0         0               0         
#   WHEELS_OFF WHEELS_ON TAXI_IN CRS_ARR_TIME ARR_TIME ARR_DELAY ARR_DELAY_NEW
# 1                                      1152     1117       -35             0
# 2                                      1152     1137       -15             0
# 3                                      1152     1111       -41             0
# 4                                      1152     1116       -36             0
# 5                                      1152     1119       -33             0
# 6                                      1152       NA        NA            NA
#   ARR_DEL15 ARR_DELAY_GROUP CANCELLED CANCELLATION_CODE DIVERTED CRS_ELAPSED_TIME
# 1         0              -2         0                          0              352
# 2         0              -1         0                          0              352
# 3         0              -2         0                          0              352
# 4         0              -2         0                          0              352
# 5         0              -2         0                          0              352
# 6        NA              NA         0                          1              352
#   ACTUAL_ELAPSED_TIME AIR_TIME FLIGHTS DISTANCE DISTANCE_GROUP CARRIER_DELAY
# 1                 316                1     2475             10              
# 2                 336                1     2475             10              
# 3                 312                1     2475             10              
# 4                 316                1     2475             10              
# 5                 317                1     2475             10              
# 6                  NA                1     2475             10              
#   WEATHER_DELAY NAS_DELAY SECURITY_DELAY LATE_AIRCRAFT_DELAY 
# 1                                                            
# 2                                                            
# 3                                                            
# 4                                                            
# 5                                                            
# 6                                                            
# 
# [[2]]
#   Visibility DryBulbCelsius DewPointCelsius RelativeHumidity WindSpeed Altimeter
# 1   4.000000       0.000000       -1.000000        92.000000  0.000000 29.690000
# 2  10.000000       7.000000       -3.000000        49.000000 11.000000 29.790000
# 3   3.000000       1.000000        0.000000        92.000000  3.000000 29.710000
# 4  10.000000       7.000000       -5.000000        42.000000 18.000000 29.710000
# 5   1.250000       3.000000        0.000000        82.000000  6.000000 29.720000
# 6  10.000000       8.000000       -4.000000        44.000000 14.000000 29.770000
#   AdjustedYear AdjustedMonth AdjustedDay AdjustedHour AirportID
# 1         2007             5           4           18     15177
# 2         2007             5           4            6     15177
# 3         2007             5           4           17     15177
# 4         2007             5           4            9     15177
# 5         2007             5           4           10     15177
# 6         2007             5           4            7     15177

```

# Exploratory Data Analysis with SparkR

## SparkR the Explorer

SparkR has a limited API for modeling. As of 1.6.1, the only supported modeling function in SparkR is a glm. There are many more available modeling functions in the R Server `RevoScaleR` library that can be computed using a Spark compute context. We will discuss this in more detail in the subsequent chapters. 

While limited in modeling, SparkR shows its versatility for data exploration. We show how easy it is to create data exploration pipelines with SparkR and open source R packages.

## Doing Data Aggregations with SparkR Efficiently

Since Spark evaluates objects lazily, tremendous speedups can be achieved by putting a little thought into our data analysis pipelines. In ths section, we will analyze the average arrival delay for flights and group them by carrier, origin and destination. These few feature variables are the only ones we need, so we can remove the redundant columns.

```{r-sparkr-select, eval = FALSE}

select_cols <- function(sparkDF = airDF) {
  
  library(magrittr)
  
  sparkDF %>% 
    SparkR::select(airDF$FL_DATE, airDF$DAY_OF_WEEK,
                   airDF$UNIQUE_CARRIER, airDF$ORIGIN,
                   airDF$DEST, airDF$ARR_DELAY) -> skinny_df
  
  skinny_df %<>% SparkR::rename(
    flight_date = skinny_df$FL_DATE,
    day_of_week = skinny_df$DAY_OF_WEEK,
    carrier = skinny_df$UNIQUE_CARRIER, 
    origin = skinny_df$ORIGIN,
    destination = skinny_df$DEST, 
    arrival_delay = skinny_df$ARR_DELAY
  )
  
  
  return(skinny_df)
  
}

air_df <- select_cols()

```

The function above creates a transformation on our airlines dataset and renames the columns we need for our analysis. At this point, we don't have any actions yet, so this is simply a promise the Spark interpreter has given us for later evaluation.

## From Spark DataFrames to Local Dataframes

For our next step, we will group by carrier, origin and destination, and calculate the average arrival delay. Our resulting dataframe should be rather condensed, so we will collect our results and save them to a local R `data.frame`. Observe how simple it is to create a pipeline that starts with a Spark DataFrame and outputs a local data.frame you can interact with locally.

```{r-arrdelay, eval = FALSE}

agg_delay <- function(airdf = air_df) {
  
  library(magrittr)
  
  airdf %>% SparkR::group_by(airdf$carrier,
                             airdf$origin,
                             airdf$destination) %>% 
    SparkR::summarize(counts = n(airdf$arrival_delay),
                      ave_delay = mean(airdf$arrival_delay)) -> summary_df
  
  return(summary_df)
  
}

agg_df <- agg_delay()
agg_df_local <- agg_df %>% collect() %>% dplyr::tbl_df
save(agg_df_local, file = "aggflightslocal.RData")

```


If you are familiar with the dplyr grammar of data manipulation, you should be ecstatic by how your knowledge transfers over directly to manipulating Spark dataframes (and you'll probably just wonder why Spark DataFrames don't just have a supported backend by dplyr yet). We saved our local data.frame to disk so we don't have to re-run the Spark datasteps again.

## Plotting Results

We deliberately kept the __carrier__ column in our analysis, in case we wanted to visualize or analyze delays by that feature. For now, let us narrow our focus to simply the routes of our flights. 

```{r-route-delays}
# load the agg_df_local calculated above
load("aggflightslocal.RData")

delays_routes <- function(delay_df = agg_df_local) {
  
  library(dplyr)
  
  delay_df %>%
    group_by(origin, destination) %>%
    summarize(total = sum(counts), 
              arrival_delay = weighted.mean(ave_delay, counts)) -> route_delays
  
  return(route_delays)
 
  
}

delays_routes()

```

Let us make a heatmap of the delays, by picking just a few routes. We will use the `ggplot` library to make our base plot, and then use the `plotly` package to make our plot more interactive!

```{r-plot-delays, message = FALSE}

library(ggplot2)

plot_route_delays <- function(min_routes = 10) {
  
  library(dplyr)
  library(ggplot2)
  
  gplot <- delays_routes() %>%
    filter(total > min_routes) %>% 
    arrange(desc(total)) %>% 
    filter(origin %in% c("JFK", "LGA", "IAD", "DCA",
                         "ATL", "DFW", "ORD", "IAH", 
                         "DEN", "CLT"),
           destination %in% c("ATL", "BDL", "BOS", "JFK", 
                              "IAD", "LGA", "DCA", "IAD",
                              "DFW", "ORD", "IAH", "DEN", 
                              "CLT")) %>% 
    ggplot(aes(x = origin, y = destination, fill = arrival_delay)) + 
    geom_tile(color = "white") + 
    scale_fill_gradient(low = "white", high = "steelblue")
  
  return(gplot)
  
}

gplot <- plot_route_delays(100) + theme_bw()
library(plotly)
ggplotly(gplot, width = 650)

```



# Data Manipulation with SparkR

Now that we have our two datasets saved as Spark DataFrames, we can conduct standard data manipulation techniques to visualize and explore our data. 

First, we'll use the `rename` function to rename our columns, and the `select` function to select the columns we need. We'll also transform the  These SparkR functions look just like the verbs from the `dplyr` package for data manipulation, but are designed to work with Spark DataFrames.

```{r-rename-air, eval = FALSE}

system.time(airDF <- rename(airDF,
                            ArrDel15 = airDF$ARR_DEL15,
                            Year = airDF$YEAR,
                            Month = airDF$MONTH,
                            DayofMonth = airDF$DAY_OF_MONTH,
                            DayOfWeek = airDF$DAY_OF_WEEK,
                            Carrier = airDF$UNIQUE_CARRIER,
                            OriginAirportID = airDF$ORIGIN_AIRPORT_ID,
                            DestAirportID = airDF$DEST_AIRPORT_ID,
                            CRSDepTime = airDF$CRS_DEP_TIME,
                            CRSArrTime =  airDF$CRS_ARR_TIME,
                            Distance = airDF$DISTANCE,
                            DepDelay = airDF$DEP_DELAY,
                            ArrDelay = airDF$ARR_DELAY
                            )
            )
  #  user  system elapsed 
  # 0.136   0.000   0.242 

# Select desired columns from the flight data. 
varsToKeep <- c("ArrDel15", "Year", "Month", "DayofMonth", "DayOfWeek", "Carrier",
                "OriginAirportID", "DestAirportID", "CRSDepTime", "CRSArrTime",
                "Distance", "DepDelay", "ArrDelay")
system.time(airDF <- select(airDF, varsToKeep))
  #  user  system elapsed 
  # 0.064   0.000   0.112 

# Round down scheduled departure time to full hour.
system.time(airDF$CRSDepTime <- floor(airDF$CRSDepTime / 100))
  # user  system elapsed 
  #  0.00    0.00    0.06 
```

## Data Aggregations

SparkR is great at merges, and data aggregation. For instance, suppose we want to see the average departure delay for each carrier and arrange it in descending order. The following example shows just how easy the syntax for SparkR is.

```{r-groupsummary, eval = FALSE}
sum_df <- airDF %>% select("Carrier", "DepDelay") %>% 
  group_by(airDF$Carrier) %>% 
  summarize(count = n(airDF$Carrier), 
            ave_delay = mean(airDF$DepDelay))
   # user  system elapsed 
  # 0.024   0.000   0.055 
```

The syntax is almost exactly like the syntax from the dplyr package, and the `%>%` operator makes chaining the additive methods exceptionally simple. Note that the above operation will not be run until we call an action upon the `sum_df.` As of right now it is a series of transformations, so it is a recipe for doing some computations, but the actual evaluation has been deferred until we call an action.

## Collecting Results to Local Dataframes

In order to evaluate and bring the summarized data into an R `data.frame`, we can use the `collect` action.

```{r-collect, eval = FALSE}
sum_local <- sum_df %>% collect()
  #  user  system elapsed 
  # 0.616   0.536 337.758 
library(dplyr)
sum_local %>% arrange(desc(ave_delay))
```

## Dimple Bar Charts

Now that our data resides as a local data.frame, we can plot it using any R plotting library.

```{r-dimple-plot}
load("local_df.RData")
library(rcdimple)
sum_local %>% 
  dimple(x ="Carrier", y = "ave_delay", z =  "count", type = "bar") %>%
  add_title(html = "<h4>Average Delay in Minutes by Carrier</h4>" ) %>% 
  zAxis(outputFormat = "#,### ")

```

In order to make the weather data correspond to the airline data, let us aggregate it by date and airport, and obtain it's average value. If you are familiar with the dplyr package, you should be very familiar with the syntax provided by SparkR. 

```{r-agg-weather, eval = FALSE}
weatherAgg <- weatherDF %>% 
  SparkR::group_by("AdjustedYear", "AdjustedMonth", "AdjustedDay", "AdjustedHour", "AirportID") %>%
  SparkR::summarize(Visibility = mean(weatherDF$Visibility),
                    DryBulbCelsius = mean(weatherDF$DryBulbCelsius),
                    DewPointCelsius = mean(weatherDF$DewPointCelsius),
                    RelativeHumidity = mean(weatherDF$RelativeHumidity),
                    WindSpeed = mean(weatherDF$RelativeHumidity),
                    Altimeter = mean(weatherDF$Altimeter))


```


## Merging Data

We can use SparkR for merging data sets as well. Let's merge the airlines dataset with the weather dataset. We'll first add weather data to the origination airport, and then add it to the destination airport. To keep our data in manageable size, we will remove the redundant columns. Finally, we save the DataFrame to a CSV file, stored in HDFS so that we may access it later.

```{r-merge-dfs, eval = FALSE}

joinedDF <- SparkR::join(
  airDF,
  weatherAgg,
  airDF$OriginAirportID == weatherAgg$AirportID &
    airDF$Year == weatherAgg$AdjustedYear &
    airDF$Month == weatherAgg$AdjustedMonth &
    airDF$DayofMonth == weatherAgg$AdjustedDay &
    airDF$CRSDepTime == weatherAgg$AdjustedHour,
  joinType = "left_outer"
)

vars <- names(joinedDF)
varsToDrop <- c('AdjustedYear', 'AdjustedMonth', 'AdjustedDay', 'AdjustedHour', 'AirportID')
varsToKeep <- vars[!(vars %in% varsToDrop)]
joinedDF1 <- select(joinedDF, varsToKeep)

joinedDF2 <- rename(joinedDF1,
                    VisibilityOrigin = joinedDF1$Visibility,
                    DryBulbCelsiusOrigin = joinedDF1$DryBulbCelsius,
                    DewPointCelsiusOrigin = joinedDF1$DewPointCelsius,
                    RelativeHumidityOrigin = joinedDF1$RelativeHumidity,
                    WindSpeedOrigin = joinedDF1$WindSpeed,
                    AltimeterOrigin = joinedDF1$Altimeter
)


joinedDF3 <- join(
  joinedDF2,
  weatherAgg,
  airDF$DestAirportID == weatherAgg$AirportID &
    airDF$Year == weatherAgg$AdjustedYear &
    airDF$Month == weatherAgg$AdjustedMonth &
    airDF$DayofMonth == weatherAgg$AdjustedDay &
    airDF$CRSDepTime == weatherAgg$AdjustedHour,
  joinType = "left_outer"
)

# Remove redundant columns
vars <- names(joinedDF3)
varsToDrop <- c('AdjustedYear', 'AdjustedMonth', 'AdjustedDay', 'AdjustedHour', 'AirportID')
varsToKeep <- vars[!(vars %in% varsToDrop)]
joinedDF4 <- select(joinedDF3, varsToKeep)

joinedDF5 <- rename(joinedDF4,
                    VisibilityDest = joinedDF4$Visibility,
                    DryBulbCelsiusDest = joinedDF4$DryBulbCelsius,
                    DewPointCelsiusDest = joinedDF4$DewPointCelsius,
                    RelativeHumidityDest = joinedDF4$RelativeHumidity,
                    WindSpeedDest = joinedDF4$WindSpeed,
                    AltimeterDest = joinedDF4$Altimeter
                    )


joinedDF5 <- repartition(joinedDF5, 80) 

# write result to directory of CSVs
write.df(joinedDF5, file.path("/user/RevoShare/alizaidi/delayDataLarge",
                              "JoinAirWeatherDelay"),
         "com.databricks.spark.csv", "overwrite", 
         header = "true")

# We can shut down the SparkR Spark context now
sparkR.stop()

```



