--- 
title: "Scalable Machine Learning and Data Science with Microsoft R Server and Spark"
author: "Ali Zaidi, Machine Learning and Data Science, Microsoft"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "These are (tentatively) rough notes showcasing some tips on conducting large scale data analysis with R, Spark, and Microsoft R Server. The focus is primarily on machine learning with Azure HDInsight platform, but review other in-memory, large-scale data analysis platforms, such as R Services with SQL Server 2016, and discuss how to utilize BI tools such as PowerBI and Shiny for dynamic reporting, and report generation."
---

# Abstract {-}
## Scalable Machine Learning with Microsoft R Server and Spark

This collection of notes in progress will help you get started on using Microsoft R Server and Spark with the Azure HDInsight platform. 

## Useful Resources
There are a number of useful resources on Spark, R, and Azure HDInsight. I have listed a few that I found particularly useful.

### Spark
+ [Spark Documentation Home Page](http://spark.apache.org/docs/latest/index.html)
+ [The Founding Paper](http://people.csail.mit.edu/matei/papers/2010/hotcloud_spark.pdf)
+ [Origination of RDDs](https://www.cs.berkeley.edu/~matei/papers/2012/nsdi_spark.pdf)
+ [MLlib -- Machine Learning in Spark](http://arxiv.org/pdf/1505.06807.pdf)
+ [Spark Programming Guide](https://spark.apache.org/docs/latest/programming-guide.html)
+ [Spark Packages](http://spark-packages.org/)
+ [Spark Summit](https://spark-summit.org/east-2016/schedule/)
+ [Jacek Laskowski - Mastering Apache Spark](https://www.gitbook.com/book/jaceklaskowski/mastering-apache-spark/details)
+ 

### Microsoft R Server
+ [Landing Page for R Server](https://www.microsoft.com/en-us/server-cloud/products/r-server/)
+ [Documentation](https://packages.revolutionanalytics.com/doc/8.0.0/)
+ 

### Azure HDInsight
+ [HDInsight Documentation Home Page](https://azure.microsoft.com/en-us/documentation/services/hdinsight/)
+ [Machine Learning with HDInsight Spark](https://azure.microsoft.com/en-us/documentation/articles/hdinsight-apache-spark-machine-learning-mllib-ipython/)
+ [R Server on HDInsight](https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-r-server-overview/)